baseURL = 'https://blog.megabits.xyz/'
languageCode = 'zh-cn'
title = '🍤 金鱼的记忆仓库'

theme = "paper"
enableInlineShortcodes = true

[params]
  author = "Megabits"
  description = "你好，这些东西是一条鱼的记忆。假如他忘了什么的话，记得去提醒他。"
  twitter = 'Megabits_mzq'
  github = 'megabitsenmzq'

[menu]
  [[menu.main]]
    identifier = "dev"
    name = "技术文章"
    url = "/dev-posts/"
    weight = 10

  [[menu.main]]
    identifier = "cookie"
    name = "送我曲奇"
    url = "https://buymeacoffee.com/megabits"
    weight = 20

[taxonomies]
    tag = "tags"