baseURL = "https://megabits.xyz/"
languageCode = "zh-CN"
title = "🍤 金鱼的记忆仓库"
Theme = "hugo-paper"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true

[params]
  author = "Megabits"
  description = "你好，这些东西是一条鱼的记忆。假如他忘了什么的话，记得去提醒他。"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110